Repository Board-Buddy/back-end, pull requests merged in 2025-06, with the labels that each got.

#295 Feat: 모집글 리스트 조회 로직 변경
  src/main/java/sumcoda/boardbuddy/controller/GatherArticleController.java
  src/main/java/sumcoda/boardbuddy/repository/gatherArticle/GatherArticleRepositoryCustom.java
  src/main/java/sumcoda/boardbuddy/repository/gatherArticle/GatherArticleRepositoryCustomImpl.java
  src/main/java/sumcoda/boardbuddy/service/GatherArticleService.java
Labels: feat

#297 [Fix] 입장한 채팅방 목록 조회시 500(Internal Server Error) 응답 반환 이슈 해결
  src/main/java/sumcoda/boardbuddy/dto/ChatMessageResponse.java
  src/main/java/sumcoda/boardbuddy/dto/ChatRoomResponse.java
  src/main/java/sumcoda/boardbuddy/dto/GatherArticleResponse.java
  src/main/java/sumcoda/boardbuddy/repository/chatRoom/ChatRoomRepositoryCustom.java
  src/main/java/sumcoda/boardbuddy/repository/chatRoom/ChatRoomRepositoryCustomImpl.java
  src/main/java/sumcoda/boardbuddy/service/ChatRoomService.java
  src/main/java/sumcoda/boardbuddy/util/ChatRoomUtil.java
Labels: bug, fix, !HOTFIX

#301 [Fix#300] ddl-auto 설정 변경 및 test, admin 계정 생성 로직 비활성화
  src/main/java/sumcoda/boardbuddy/config/InitializerConfig.java
  src/main/resources/application-prod.yml
Labels: fix, refactoring
